In [1]:
#NumPy =  Numeric Python

In [2]:
#any array operations in Python is done using NumPy library.

In [3]:
import numpy as np

In [4]:
np.__version__

'1.23.5'

In [5]:
arr= np.array(range(10))

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
list1= [1,2,3,4,5]

In [8]:
type(list1)

list

In [9]:
arr1=np.array(list1)

In [10]:
arr1

array([1, 2, 3, 4, 5])

In [31]:
arr1.ndim

1

In [11]:
type(arr1)

numpy.ndarray

In [17]:
#create array with evenly spaced integers

arr2= np.arange(0, 10, 1)

In [18]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr3=np.linspace(0, 10, 10)

In [20]:
arr3

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [21]:
arr3,step =np.linspace(0,10,10, retstep=True)
print(arr3)
print(step)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
1.1111111111111112


In [28]:
arr4=np.random.rand(1,3)

In [29]:
arr4

array([[0.61591703, 0.07336696, 0.25053171]])

In [30]:
arr4.ndim

2

In [33]:
zeros= np.zeros((2,3))

In [34]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.random.rand(3,3)

array([[0.50902376, 0.28277549, 0.69909217],
       [0.00249394, 0.12403312, 0.45613159],
       [0.80514604, 0.41739671, 0.72270273]])

In [36]:
ones= np.ones((2,3))

In [37]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
arr5= np.ones_like(zeros)

In [39]:
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])